var user = [{
login: "Elizabeth-Evans",
id: 16964565,
avatar_url: "https://avatars.githubusercontent.com/u/16964565?v=3",
gravatar_id: "",
url: "https://api.github.com/users/Elizabeth-Evans",
html_url: "https://github.com/Elizabeth-Evans",
followers_url: "https://api.github.com/users/Elizabeth-Evans/followers",
following_url: "https://api.github.com/users/Elizabeth-Evans/following{/other_user}",
gists_url: "https://api.github.com/users/Elizabeth-Evans/gists{/gist_id}",
starred_url: "https://api.github.com/users/Elizabeth-Evans/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/Elizabeth-Evans/subscriptions",
organizations_url: "https://api.github.com/users/Elizabeth-Evans/orgs",
repos_url: "https://api.github.com/users/Elizabeth-Evans/repos",
events_url: "https://api.github.com/users/Elizabeth-Evans/events{/privacy}",
received_events_url: "https://api.github.com/users/Elizabeth-Evans/received_events",
type: "User",
site_admin: false,
name: "Elizabeth Evans",
company: null,
blog: null,
location: null,
email: "ickabeth@gmail.com",
hireable: null,
bio: null,
public_repos: 14,
public_gists: 0,
followers: 0,
following: 0,
created_at: "2016-01-29T20:51:56Z",
updated_at: "2016-02-08T02:39:50Z"
}
]
